export interface ThemeDefinition {
  name: string
  label: string
  colors: Record<string, string>
}

export const themes: ThemeDefinition[] = [
  {
    name: 'dark',
    label: 'Dark',
    colors: {
      '--bg': '#1A1A1A',
      '--bg-surface': '#1A1A1A',
      '--bg-overlay': '#1A1A1A',
      '--bg-input': '#1A1A1A',
      '--border': '#333333',
      '--border-focus': '#4D7FFF',
      '--divider': '#2A2A2A',
      '--fg': '#C7C7C7',
      '--fg-bright': '#F0F6FC',
      '--fg-muted': '#666666',
      '--accent': '#4D7FFF',
      '--accent-hover': '#6E9AFF',
      '--tab-bg': '#252525',
      '--tab-active-bg': '#1A1A1A',
      '--tab-hover-bg': '#2A2A2A',
      '--tab-text': '#888888',
      '--tab-active-text': '#F0F6FC',
      '--color-black': '#000000',
      '--color-red': '#C91B00',
      '--color-green': '#00C200',
      '--color-yellow': '#C7C400',
      '--color-blue': '#0225C7',
      '--color-magenta': '#CA30C7',
      '--color-cyan': '#00C5C7',
      '--color-white': '#C7C7C7',
      '--color-bright-black': '#686868',
      '--color-bright-red': '#FF6E67',
      '--color-bright-green': '#5FFA68',
      '--color-bright-yellow': '#FFFC67',
      '--color-bright-blue': '#6871FF',
      '--color-bright-magenta': '#FF77FF',
      '--color-bright-cyan': '#60FDFF',
      '--color-bright-white': '#FFFFFF',
    },
  },
  {
    name: 'light',
    label: 'Light',
    colors: {
      '--bg': '#FFFFFF',
      '--bg-surface': '#F5F5F5',
      '--bg-overlay': '#FFFFFF',
      '--bg-input': '#FFFFFF',
      '--border': '#E0E0E0',
      '--border-focus': '#2563EB',
      '--divider': '#EEEEEE',
      '--fg': '#333333',
      '--fg-bright': '#111111',
      '--fg-muted': '#999999',
      '--accent': '#2563EB',
      '--accent-hover': '#3B82F6',
      '--tab-bg': '#F5F5F5',
      '--tab-active-bg': '#FFFFFF',
      '--tab-hover-bg': '#EEEEEE',
      '--tab-text': '#666666',
      '--tab-active-text': '#111111',
      '--color-black': '#000000',
      '--color-red': '#C91B00',
      '--color-green': '#00A600',
      '--color-yellow': '#999900',
      '--color-blue': '#0000B2',
      '--color-magenta': '#B200B2',
      '--color-cyan': '#00A6B2',
      '--color-white': '#BFBFBF',
      '--color-bright-black': '#666666',
      '--color-bright-red': '#E50000',
      '--color-bright-green': '#00D900',
      '--color-bright-yellow': '#E5E500',
      '--color-bright-blue': '#0000FF',
      '--color-bright-magenta': '#E500E5',
      '--color-bright-cyan': '#00E5E5',
      '--color-bright-white': '#E5E5E5',
    },
  },
  {
    name: 'dracula',
    label: 'Dracula',
    colors: {
      '--bg': '#282A36',
      '--bg-surface': '#282A36',
      '--bg-overlay': '#282A36',
      '--bg-input': '#44475A',
      '--border': '#44475A',
      '--border-focus': '#BD93F9',
      '--divider': '#44475A',
      '--fg': '#F8F8F2',
      '--fg-bright': '#FFFFFF',
      '--fg-muted': '#6272A4',
      '--accent': '#BD93F9',
      '--accent-hover': '#CFA9FF',
      '--tab-bg': '#21222C',
      '--tab-active-bg': '#282A36',
      '--tab-hover-bg': '#2D2F3B',
      '--tab-text': '#6272A4',
      '--tab-active-text': '#F8F8F2',
      '--color-black': '#21222C',
      '--color-red': '#FF5555',
      '--color-green': '#50FA7B',
      '--color-yellow': '#F1FA8C',
      '--color-blue': '#BD93F9',
      '--color-magenta': '#FF79C6',
      '--color-cyan': '#8BE9FD',
      '--color-white': '#F8F8F2',
      '--color-bright-black': '#6272A4',
      '--color-bright-red': '#FF6E6E',
      '--color-bright-green': '#69FF94',
      '--color-bright-yellow': '#FFFFA5',
      '--color-bright-blue': '#D6ACFF',
      '--color-bright-magenta': '#FF92DF',
      '--color-bright-cyan': '#A4FFFF',
      '--color-bright-white': '#FFFFFF',
    },
  },
  {
    name: 'nord',
    label: 'Nord',
    colors: {
      '--bg': '#2E3440',
      '--bg-surface': '#2E3440',
      '--bg-overlay': '#2E3440',
      '--bg-input': '#3B4252',
      '--border': '#3B4252',
      '--border-focus': '#88C0D0',
      '--divider': '#3B4252',
      '--fg': '#D8DEE9',
      '--fg-bright': '#ECEFF4',
      '--fg-muted': '#4C566A',
      '--accent': '#88C0D0',
      '--accent-hover': '#8FBCBB',
      '--tab-bg': '#2E3440',
      '--tab-active-bg': '#3B4252',
      '--tab-hover-bg': '#434C5E',
      '--tab-text': '#4C566A',
      '--tab-active-text': '#ECEFF4',
      '--color-black': '#3B4252',
      '--color-red': '#BF616A',
      '--color-green': '#A3BE8C',
      '--color-yellow': '#EBCB8B',
      '--color-blue': '#81A1C1',
      '--color-magenta': '#B48EAD',
      '--color-cyan': '#88C0D0',
      '--color-white': '#E5E9F0',
      '--color-bright-black': '#4C566A',
      '--color-bright-red': '#BF616A',
      '--color-bright-green': '#A3BE8C',
      '--color-bright-yellow': '#EBCB8B',
      '--color-bright-blue': '#81A1C1',
      '--color-bright-magenta': '#B48EAD',
      '--color-bright-cyan': '#8FBCBB',
      '--color-bright-white': '#ECEFF4',
    },
  },
  {
    name: 'monokai',
    label: 'Monokai',
    colors: {
      '--bg': '#272822',
      '--bg-surface': '#272822',
      '--bg-overlay': '#272822',
      '--bg-input': '#3E3D32',
      '--border': '#3E3D32',
      '--border-focus': '#F92672',
      '--divider': '#3E3D32',
      '--fg': '#F8F8F2',
      '--fg-bright': '#FFFFFF',
      '--fg-muted': '#75715E',
      '--accent': '#F92672',
      '--accent-hover': '#FF4D8D',
      '--tab-bg': '#1E1F1C',
      '--tab-active-bg': '#272822',
      '--tab-hover-bg': '#2D2E28',
      '--tab-text': '#75715E',
      '--tab-active-text': '#F8F8F2',
      '--color-black': '#272822',
      '--color-red': '#F92672',
      '--color-green': '#A6E22E',
      '--color-yellow': '#F4BF75',
      '--color-blue': '#66D9EF',
      '--color-magenta': '#AE81FF',
      '--color-cyan': '#A1EFE4',
      '--color-white': '#F8F8F2',
      '--color-bright-black': '#75715E',
      '--color-bright-red': '#F92672',
      '--color-bright-green': '#A6E22E',
      '--color-bright-yellow': '#F4BF75',
      '--color-bright-blue': '#66D9EF',
      '--color-bright-magenta': '#AE81FF',
      '--color-bright-cyan': '#A1EFE4',
      '--color-bright-white': '#F9F8F5',
    },
  },
  {
    name: 'solarized',
    label: 'Solarized',
    colors: {
      '--bg': '#002B36',
      '--bg-surface': '#002B36',
      '--bg-overlay': '#002B36',
      '--bg-input': '#073642',
      '--border': '#073642',
      '--border-focus': '#268BD2',
      '--divider': '#073642',
      '--fg': '#839496',
      '--fg-bright': '#FDF6E3',
      '--fg-muted': '#586E75',
      '--accent': '#268BD2',
      '--accent-hover': '#2AA1E3',
      '--tab-bg': '#002B36',
      '--tab-active-bg': '#073642',
      '--tab-hover-bg': '#073642',
      '--tab-text': '#586E75',
      '--tab-active-text': '#93A1A1',
      '--color-black': '#073642',
      '--color-red': '#DC322F',
      '--color-green': '#859900',
      '--color-yellow': '#B58900',
      '--color-blue': '#268BD2',
      '--color-magenta': '#D33682',
      '--color-cyan': '#2AA198',
      '--color-white': '#EEE8D5',
      '--color-bright-black': '#586E75',
      '--color-bright-red': '#CB4B16',
      '--color-bright-green': '#859900',
      '--color-bright-yellow': '#B58900',
      '--color-bright-blue': '#268BD2',
      '--color-bright-magenta': '#6C71C4',
      '--color-bright-cyan': '#2AA198',
      '--color-bright-white': '#FDF6E3',
    },
  },
]

export function getThemeByName(name: string): ThemeDefinition {
  return themes.find((t) => t.name === name) || themes[0]
}

export function applyThemeToDOM(theme: ThemeDefinition) {
  const root = document.documentElement
  for (const [key, value] of Object.entries(theme.colors)) {
    root.style.setProperty(key, value)
  }
}

export function getXtermTheme(theme: ThemeDefinition) {
  const c = theme.colors
  return {
    background: c['--bg'],
    foreground: c['--fg'],
    cursor: c['--fg-muted'],
    cursorAccent: c['--color-black'],
    selectionBackground: 'rgba(77,127,255,0.35)',
    black: c['--color-black'],
    red: c['--color-red'],
    green: c['--color-green'],
    yellow: c['--color-yellow'],
    blue: c['--color-blue'],
    magenta: c['--color-magenta'],
    cyan: c['--color-cyan'],
    white: c['--color-white'],
    brightBlack: c['--color-bright-black'],
    brightRed: c['--color-bright-red'],
    brightGreen: c['--color-bright-green'],
    brightYellow: c['--color-bright-yellow'],
    brightBlue: c['--color-bright-blue'],
    brightMagenta: c['--color-bright-magenta'],
    brightCyan: c['--color-bright-cyan'],
    brightWhite: c['--color-bright-white'],
  }
}
